openapi: 3.0.0
info:
  title: Stripe Apple Pay API
paths:
  /v1/apple_pay/domains:
    get:
      description: <p>List apple pay domains.</p>
      tags:
        - V1
        - Apple_pay
        - Domains
    post:
      description: <p>Create an apple pay domain.</p>
      tags:
        - V1
        - Apple_pay
        - Domains
  /v1/apple_pay/domains/{domain}:
    delete:
      description: <p>Delete an apple pay domain.</p>
      tags:
        - V1
        - Apple_pay
        - Domains
        - Domain
    get:
      description: <p>Retrieve an apple pay d
      tags:
        - V1
        - Apple_pay
        - Domains
        - Doma
