openapi: 3.0.0
info:
  title: Stripe Billing API
paths:
  /v1/billing_portal/configurations:
    get:
      description: >-
        <p>Returns a list of configurations that describe the functionality of
        the customer portal.</p>
      tags:
        - V1
        - Billing_portal
        - Configurations
    post:
      description: >-
        <p>Creates a configuration that describes the functionality and behavior
        of a PortalSession</p>
      tags:
        - V1
        - Billing_portal
        - Configurations
  /v1/billing_portal/configurations/{configuration}:
    get:
      description: >-
        <p>Retrieves a configuration that describes the functionality of the
        customer portal.</p>
      tags:
        - V1
        - Billing_portal
        - Configurations
        - Configuration
    post:
      description: >-
        <p>Updates a configuration that describes the functionality of the
        customer portal.</p>
      tags:
        - V1
        - Billing_portal
        - Configurations
        - Configuration
  /v1/billing_portal/sessions:
    post:
      description: <p>Creates a session of the customer p
      tags:
        - V1
        - Billing_portal
        - Configurations
        - Configuration
        - Sessio
