openapi: 3.0.0
info:
  title: Stripe Ephemeral Keys API
paths:
  /v1/ephemeral_keys:
    post:
      description: <p>Creates a short-lived API key for a given resource.</p>
      tags:
        - V1
        - Ephemeral_keys
  /v1/ephemeral_keys/{key}:
    delete:
      description: <p>Invalidates a short-lived API key for a given res
      tags:
        - V1
        - Ephemeral_keys
        - K
