openapi: 3.0.0
info:
  title: Stripe Issuing API
paths:
  /v1/issuing/authorizations:
    get:
      description: >-
        <p>Returns a list of Issuing <code>Authorization</code> objects. The
        objects are sorted in descending order by creation date, with the most
        recently created object appearing first.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
  /v1/issuing/authorizations/{authorization}:
    get:
      description: <p>Retrieves an Issuing <code>Authorization</code> object.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
    post:
      description: >-
        <p>Updates the specified Issuing <code>Authorization</code> object by
        setting the values of the parameters passed. Any parameters not provided
        will be left unchanged.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
  /v1/issuing/authorizations/{authorization}/approve:
    post:
      description: >-
        <p>[Deprecated] Approves a pending Issuing <code>Authorization</code>
        object. This request should be made within the timeout window of the <a
        href="/docs/issuing/controls/real-time-authorizations">real-time
        authorization</a> flow. 

        This method is deprecated. Instead, <a
        href="/docs/issuing/controls/real-time-authorizations#authorization-handling">respond
        directly to the webhook request to approve an authorization</a>.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
  /v1/issuing/authorizations/{authorization}/decline:
    post:
      description: >-
        <p>[Deprecated] Declines a pending Issuing <code>Authorization</code>
        object. This request should be made within the timeout window of the <a
        href="/docs/issuing/controls/real-time-authorizations">real time
        authorization</a> flow.

        This method is deprecated. Instead, <a
        href="/docs/issuing/controls/real-time-authorizations#authorization-handling">respond
        directly to the webhook request to decline an authorization</a>.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
  /v1/issuing/cardholders:
    get:
      description: >-
        <p>Returns a list of Issuing <code>Cardholder</code> objects. The
        objects are sorted in descending order by creation date, with the most
        recently created object appearing first.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
    post:
      description: >-
        <p>Creates a new Issuing <code>Cardholder</code> object that can be
        issued cards.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
  /v1/issuing/cardholders/{cardholder}:
    get:
      description: <p>Retrieves an Issuing <code>Cardholder</code> object.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
    post:
      description: >-
        <p>Updates the specified Issuing <code>Cardholder</code> object by
        setting the values of the parameters passed. Any parameters not provided
        will be left unchanged.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
  /v1/issuing/cards:
    get:
      description: >-
        <p>Returns a list of Issuing <code>Card</code> objects. The objects are
        sorted in descending order by creation date, with the most recently
        created object appearing first.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
    post:
      description: <p>Creates an Issuing <code>Card</code> object.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
  /v1/issuing/cards/{card}:
    get:
      description: <p>Retrieves an Issuing <code>Card</code> object.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
    post:
      description: >-
        <p>Updates the specified Issuing <code>Card</code> object by setting the
        values of the parameters passed. Any parameters not provided will be
        left unchanged.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
  /v1/issuing/disputes:
    get:
      description: >-
        <p>Returns a list of Issuing <code>Dispute</code> objects. The objects
        are sorted in descending order by creation date, with the most recently
        created object appearing first.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
    post:
      description: >-
        <p>Creates an Issuing <code>Dispute</code> object. Individual pieces of
        evidence within the <code>evidence</code> object are optional at this
        point. Stripe only validates that required evidence is present during
        submission. Refer to <a
        href="/docs/issuing/purchases/disputes#dispute-reasons-and-evidence">Dispute
        reasons and evidence</a> for more details about evidence
        requirements.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
  /v1/issuing/disputes/{dispute}:
    get:
      description: <p>Retrieves an Issuing <code>Dispute</code> object.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
        - Dispute
    post:
      description: >-
        <p>Updates the specified Issuing <code>Dispute</code> object by setting
        the values of the parameters passed. Any parameters not provided will be
        left unchanged. Properties on the <code>evidence</code> object can be
        unset by passing in an empty string.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
        - Dispute
  /v1/issuing/disputes/{dispute}/submit:
    post:
      description: >-
        <p>Submits an Issuing <code>Dispute</code> to the card network. Stripe
        validates that all evidence fields required for the dispute’s reason are
        present. For more details, see <a
        href="/docs/issuing/purchases/disputes#dispute-reasons-and-evidence">Dispute
        reasons and evidence</a>.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
        - Dispute
        - Submit
  /v1/issuing/settlements:
    get:
      description: >-
        <p>Returns a list of Issuing <code>Settlement</code> objects. The
        objects are sorted in descending order by creation date, with the most
        recently created object appearing first.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
        - Dispute
        - Submit
        - Settlements
  /v1/issuing/settlements/{settlement}:
    get:
      description: <p>Retrieves an Issuing <code>Settlement</code> object.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
        - Dispute
        - Submit
        - Settlements
        - Settlement
    post:
      description: >-
        <p>Updates the specified Issuing <code>Settlement</code> object by
        setting the values of the parameters passed. Any parameters not provided
        will be left unchanged.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
        - Dispute
        - Submit
        - Settlements
        - Settlement
  /v1/issuing/tokens:
    get:
      description: <p>Lists all Issuing <code>Token</code> objects for a given card.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
        - Dispute
        - Submit
        - Settlements
        - Settlement
        - Tokens
  /v1/issuing/tokens/{token}:
    get:
      description: <p>Retrieves an Issuing <code>Token</code> object.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
        - Dispute
        - Submit
        - Settlements
        - Settlement
        - Tokens
        - Token
    post:
      description: >-
        <p>Attempts to update the specified Issuing <code>Token</code> object to
        the status specified.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
        - Dispute
        - Submit
        - Settlements
        - Settlement
        - Tokens
        - Token
  /v1/issuing/transactions:
    get:
      description: >-
        <p>Returns a list of Issuing <code>Transaction</code> objects. The
        objects are sorted in descending order by creation date, with the most
        recently created object appearing first.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
        - Dispute
        - Submit
        - Settlements
        - Settlement
        - Tokens
        - Token
        - Transactions
  /v1/issuing/transactions/{transaction}:
    get:
      description: <p>Retrieves an Issuing <code>Transaction</code> object.</p>
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
        - Dispute
        - Submit
        - Settlements
        - Settlement
        - Tokens
        - Token
        - Transactions
        - Transaction
    post:
      description: >-
        <p>Updates the specified Issuing <code>Transaction</code> object by
        setting the values of the parameters passed. Any parameters not provided
        will be left unch
      tags:
        - V1
        - Issuing
        - Authorizations
        - Authorization
        - Approve
        - Decline
        - Cardholders
        - Cardholder
        - Cards
        - Card
        - Disputes
        - Dispute
        - Submit
        - Settlements
        - Settlement
        - Tokens
        - Token
        - Transactions
        - Transacti
