openapi: 3.0.0
info:
  title: Stripe Payment Links API
paths:
  /v1/payment_links:
    get:
      description: <p>Returns a list of your payment links.</p>
      tags:
        - V1
        - Payment_links
    post:
      description: <p>Creates a payment link.</p>
      tags:
        - V1
        - Payment_links
  /v1/payment_links/{payment_link}:
    get:
      description: <p>Retrieve a payment link.</p>
      tags:
        - V1
        - Payment_links
        - Payment_link
    post:
      description: <p>Updates a payment link.</p>
      tags:
        - V1
        - Payment_links
        - Payment_link
  /v1/payment_links/{payment_link}/line_items:
    get:
      description: >-
        <p>When retrieving a payment link, there is an includable
        <strong>line_items</strong> property containing the first handful of
        those items. There is also a URL where you can retrieve the full
        (paginated) list of line 
      tags:
        - V1
        - Payment_links
        - Payment_link
        - Line_ite
