openapi: 3.0.0
info:
  title: Stripe Radar API
paths:
  /v1/radar/early_fraud_warnings:
    get:
      description: <p>Returns a list of early fraud warnings.</p>
      tags:
        - V1
        - Radar
        - Early_fraud_warnings
  /v1/radar/early_fraud_warnings/{early_fraud_warning}:
    get:
      description: >-
        <p>Retrieves the details of an early fraud warning that has previously
        been created. </p>


        <p>Please refer to the <a href="#early_fraud_warning_object">early fraud
        warning</a> object reference for more details.</p>
      tags:
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
  /v1/radar/value_list_items:
    get:
      description: >-
        <p>Returns a list of <code>ValueListItem</code> objects. The objects are
        sorted in descending order by creation date, with the most recently
        created object appearing first.</p>
      tags:
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
    post:
      description: >-
        <p>Creates a new <code>ValueListItem</code> object, which is added to
        the specified parent value list.</p>
      tags:
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
  /v1/radar/value_list_items/{item}:
    delete:
      description: >-
        <p>Deletes a <code>ValueListItem</code> object, removing it from its
        parent value list.</p>
      tags:
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
    get:
      description: <p>Retrieves a <code>ValueListItem</code> object.</p>
      tags:
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
  /v1/radar/value_lists:
    get:
      description: >-
        <p>Returns a list of <code>ValueList</code> objects. The objects are
        sorted in descending order by creation date, with the most recently
        created object appearing first.</p>
      tags:
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
        - Value_lists
    post:
      description: >-
        <p>Creates a new <code>ValueList</code> object, which can then be
        referenced in rules.</p>
      tags:
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
        - Value_lists
  /v1/radar/value_lists/{value_list}:
    delete:
      description: >-
        <p>Deletes a <code>ValueList</code> object, also deleting any items
        contained within the value list. To be deleted, a value list must not be
        referenced in any rules.</p>
      tags:
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
        - Value_lists
        - Value_list
    get:
      description: <p>Retrieves a <code>ValueList</code> object.</p>
      tags:
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
        - Value_lists
        - Value_list
    post:
      description: >-
        <p>Updates a <code>ValueList</code> object by setting the values of the
        parameters passed. Any parameters not provided will be left unchanged.
        Note that <code>item_type</code> is immu
      tags:
        - V1
        - Radar
        - Early_fraud_warnings
        - Early_fraud_warning
        - Value_list_items
        - Item
        - Value_lists
        - Value_li
