openapi: 3.0.0
info:
  title: Stripe Shipping Rates API
paths:
  /v1/shipping_rates:
    get:
      description: <p>Returns a list of your shipping rates.</p>
      tags:
        - V1
        - Shipping_rates
    post:
      description: <p>Creates a new shipping rate object.</p>
      tags:
        - V1
        - Shipping_rates
  /v1/shipping_rates/{shipping_rate_token}:
    get:
      description: <p>Returns the shipping rate object with the given ID.</p>
      tags:
        - V1
        - Shipping_rates
        - Shipping_rate_token
    post:
      description: <p>Updates an existing shipping rate o
      tags:
        - V1
        - Shipping_rates
        - Shipping_rate_tok
