openapi: 3.0.0
info:
  title: Stripe Sigma API
paths:
  /v1/sigma/scheduled_query_runs:
    get:
      description: <p>Returns a list of scheduled query runs.</p>
      tags:
        - V1
        - Sigma
        - Scheduled_query_runs
  /v1/sigma/scheduled_query_runs/{scheduled_query_run}:
    get:
      description: <p>Retrieves the details of an scheduled que
      tags:
        - V1
        - Sigma
        - Scheduled_query_runs
        - Scheduled_query_r
