openapi: 3.0.0
info:
  title: Stripe Tax API
paths:
  /v1/tax/calculations:
    post:
      description: >-
        <p>Calculates tax based on input and returns a Tax
        <code>Calculation</code> object.</p>
      tags:
        - V1
        - Tax
        - Calculations
  /v1/tax/calculations/{calculation}/line_items:
    get:
      description: >-
        <p>Retrieves the line items of a persisted tax calculation as a
        collection.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
  /v1/tax/registrations:
    get:
      description: <p>Returns a list of Tax <code>Registration</code> objects.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
    post:
      description: <p>Creates a new Tax <code>Registration</code> object.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
  /v1/tax/registrations/{id}:
    post:
      description: >-
        <p>Updates an existing Tax <code>Registration</code> object.</p>


        <p>A registration cannot be deleted after it has been created. If you
        wish to end a registration you may do so by setting
        <code>expires_at</code>.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
  /v1/tax/settings:
    get:
      description: <p>Retrieves Tax <code>Settings</code> for a merchant.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
        - Settings
    post:
      description: >-
        <p>Updates Tax <code>Settings</code> parameters used in tax
        calculations. All parameters are editable but none can be removed once
        set.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
        - Settings
  /v1/tax/transactions/create_from_calculation:
    post:
      description: <p>Creates a Tax <code>Transaction</code> from a calculation.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
        - Settings
        - Transactions
        - Create_from_calculation
  /v1/tax/transactions/create_reversal:
    post:
      description: >-
        <p>Partially or fully reverses a previously created
        <code>Transaction</code>.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
        - Settings
        - Transactions
        - Create_from_calculation
        - Create_reversal
  /v1/tax/transactions/{transaction}:
    get:
      description: <p>Retrieves a Tax <code>Transaction</code> object.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
        - Settings
        - Transactions
        - Create_from_calculation
        - Create_reversal
        - Transaction
  /v1/tax/transactions/{transaction}/line_items:
    get:
      description: >-
        <p>Retrieves the line items of a committed standalone transaction as a
        collection.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
        - Settings
        - Transactions
        - Create_from_calculation
        - Create_reversal
        - Transaction
  /v1/tax_codes:
    get:
      description: >-
        <p>A list of <a href="https://stripe.com/docs/tax/tax-categories">all
        tax codes available</a> to add to Products in order to allow specific
        tax calculations.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
        - Settings
        - Transactions
        - Create_from_calculation
        - Create_reversal
        - Transaction
        - Tax_codes
  /v1/tax_codes/{id}:
    get:
      description: >-
        <p>Retrieves the details of an existing tax code. Supply the unique tax
        code ID and Stripe will return the corresponding tax code
        information.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
        - Settings
        - Transactions
        - Create_from_calculation
        - Create_reversal
        - Transaction
        - Tax_codes
  /v1/tax_rates:
    get:
      description: >-
        <p>Returns a list of your tax rates. Tax rates are returned sorted by
        creation date, with the most recently created tax rates appearing
        first.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
        - Settings
        - Transactions
        - Create_from_calculation
        - Create_reversal
        - Transaction
        - Tax_codes
        - Tax_rates
    post:
      description: <p>Creates a new tax rate.</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
        - Settings
        - Transactions
        - Create_from_calculation
        - Create_reversal
        - Transaction
        - Tax_codes
        - Tax_rates
  /v1/tax_rates/{tax_rate}:
    get:
      description: <p>Retrieves a tax rate with the given ID</p>
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
        - Settings
        - Transactions
        - Create_from_calculation
        - Create_reversal
        - Transaction
        - Tax_codes
        - Tax_rates
        - Tax_rate
    post:
      description: <p>Updates an existing tax
      tags:
        - V1
        - Tax
        - Calculations
        - Calculation
        - Line_items
        - Registrations
        - Id
        - Settings
        - Transactions
        - Create_from_calculation
        - Create_reversal
        - Transaction
        - Tax_codes
        - Tax_rates
        - Tax_ra
