openapi: 3.0.0
info:
  title: Stripe Terminal API
paths:
  /v1/terminal/configurations:
    get:
      description: <p>Returns a list of <code>Configuration</code> objects.</p>
      tags:
        - V1
        - Terminal
        - Configurations
    post:
      description: <p>Creates a new <code>Configuration</code> object.</p>
      tags:
        - V1
        - Terminal
        - Configurations
  /v1/terminal/configurations/{configuration}:
    delete:
      description: <p>Deletes a <code>Configuration</code> object.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
    get:
      description: <p>Retrieves a <code>Configuration</code> object.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
    post:
      description: <p>Updates a new <code>Configuration</code> object.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
  /v1/terminal/connection_tokens:
    post:
      description: >-
        <p>To connect to a reader the Stripe Terminal SDK needs to retrieve a
        short-lived connection token from Stripe, proxied through your server.
        On your backend, add an endpoint that creates and returns a connection
        token.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
  /v1/terminal/locations:
    get:
      description: <p>Returns a list of <code>Location</code> objects.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
    post:
      description: >-
        <p>Creates a new <code>Location</code> object.

        For further details, including which address fields are required in each
        country, see the <a href="/docs/terminal/fleet/locations">Manage
        locations</a> guide.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
  /v1/terminal/locations/{location}:
    delete:
      description: <p>Deletes a <code>Location</code> object.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
    get:
      description: <p>Retrieves a <code>Location</code> object.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
    post:
      description: >-
        <p>Updates a <code>Location</code> object by setting the values of the
        parameters passed. Any parameters not provided will be left
        unchanged.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
  /v1/terminal/readers:
    get:
      description: <p>Returns a list of <code>Reader</code> objects.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
        - Readers
    post:
      description: <p>Creates a new <code>Reader</code> object.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
        - Readers
  /v1/terminal/readers/{reader}:
    delete:
      description: <p>Deletes a <code>Reader</code> object.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
        - Readers
        - Reader
    get:
      description: <p>Retrieves a <code>Reader</code> object.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
        - Readers
        - Reader
    post:
      description: >-
        <p>Updates a <code>Reader</code> object by setting the values of the
        parameters passed. Any parameters not provided will be left
        unchanged.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
        - Readers
        - Reader
  /v1/terminal/readers/{reader}/cancel_action:
    post:
      description: <p>Cancels the current reader action.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
        - Readers
        - Reader
        - Cancel_action
  /v1/terminal/readers/{reader}/process_payment_intent:
    post:
      description: <p>Initiates a payment flow on a Reader.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
        - Readers
        - Reader
        - Cancel_action
        - Process_payment_intent
  /v1/terminal/readers/{reader}/process_setup_intent:
    post:
      description: <p>Initiates a setup intent flow on a Reader.</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
        - Readers
        - Reader
        - Cancel_action
        - Process_payment_intent
        - Process_setup_intent
  /v1/terminal/readers/{reader}/refund_payment:
    post:
      description: <p>Initiates a refund on a Reader</p>
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
        - Readers
        - Reader
        - Cancel_action
        - Process_payment_intent
        - Process_setup_intent
        - Refund_payment
  /v1/terminal/readers/{reader}/set_reader_display:
    post:
      description: <p>Sets reader display to show cart de
      tags:
        - V1
        - Terminal
        - Configurations
        - Configuration
        - Connection_tokens
        - Locations
        - Location
        - Readers
        - Reader
        - Cancel_action
        - Process_payment_intent
        - Process_setup_intent
        - Refund_payment
        - Set_reader_displ
