openapi: 3.0.0
info:
  title: Stripe Treasury API
paths:
  /v1/treasury/credit_reversals:
    get:
      description: <p>Returns a list of CreditReversals.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
    post:
      description: <p>Reverses a ReceivedCredit and creates a CreditReversal object.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
  /v1/treasury/credit_reversals/{credit_reversal}:
    get:
      description: >-
        <p>Retrieves the details of an existing CreditReversal by passing the
        unique CreditReversal ID from either the CreditReversal creation request
        or CreditReversal list</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
  /v1/treasury/debit_reversals:
    get:
      description: <p>Returns a list of DebitReversals.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
    post:
      description: <p>Reverses a ReceivedDebit and creates a DebitReversal object.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
  /v1/treasury/debit_reversals/{debit_reversal}:
    get:
      description: <p>Retrieves a DebitReversal object.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
  /v1/treasury/financial_accounts:
    get:
      description: <p>Returns a list of FinancialAccounts.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
    post:
      description: >-
        <p>Creates a new FinancialAccount. For now, each connected account can
        only have one FinancialAccount.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
  /v1/treasury/financial_accounts/{financial_account}:
    get:
      description: <p>Retrieves the details of a FinancialAccount.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
    post:
      description: <p>Updates the details of a FinancialAccount.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
  /v1/treasury/financial_accounts/{financial_account}/features:
    get:
      description: >-
        <p>Retrieves Features information associated with the
        FinancialAccount.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
    post:
      description: <p>Updates the Features associated with a FinancialAccount.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
  /v1/treasury/inbound_transfers:
    get:
      description: >-
        <p>Returns a list of InboundTransfers sent from the specified
        FinancialAccount.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
    post:
      description: <p>Creates an InboundTransfer.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
  /v1/treasury/inbound_transfers/{id}:
    get:
      description: <p>Retrieves the details of an existing InboundTransfer.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
  /v1/treasury/inbound_transfers/{inbound_transfer}/cancel:
    post:
      description: <p>Cancels an InboundTransfer.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
  /v1/treasury/outbound_payments:
    get:
      description: >-
        <p>Returns a list of OutboundPayments sent from the specified
        FinancialAccount.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
    post:
      description: <p>Creates an OutboundPayment.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
  /v1/treasury/outbound_payments/{id}:
    get:
      description: >-
        <p>Retrieves the details of an existing OutboundPayment by passing the
        unique OutboundPayment ID from either the OutboundPayment creation
        request or OutboundPayment list.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
  /v1/treasury/outbound_payments/{id}/cancel:
    post:
      description: <p>Cancel an OutboundPayment.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
  /v1/treasury/outbound_transfers:
    get:
      description: >-
        <p>Returns a list of OutboundTransfers sent from the specified
        FinancialAccount.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
    post:
      description: <p>Creates an OutboundTransfer.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
  /v1/treasury/outbound_transfers/{outbound_transfer}:
    get:
      description: >-
        <p>Retrieves the details of an existing OutboundTransfer by passing the
        unique OutboundTransfer ID from either the OutboundTransfer creation
        request or OutboundTransfer list.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
  /v1/treasury/outbound_transfers/{outbound_transfer}/cancel:
    post:
      description: >-
        <p>An OutboundTransfer can be canceled if the funds have not yet been
        paid out.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
  /v1/treasury/received_credits:
    get:
      description: <p>Returns a list of ReceivedCredits.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
  /v1/treasury/received_credits/{id}:
    get:
      description: >-
        <p>Retrieves the details of an existing ReceivedCredit by passing the
        unique ReceivedCredit ID from the ReceivedCredit list.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
  /v1/treasury/received_debits:
    get:
      description: <p>Returns a list of ReceivedDebits.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
        - Received_debits
  /v1/treasury/received_debits/{id}:
    get:
      description: >-
        <p>Retrieves the details of an existing ReceivedDebit by passing the
        unique ReceivedDebit ID from the ReceivedDebit list</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
        - Received_debits
  /v1/treasury/transaction_entries:
    get:
      description: <p>Retrieves a list of TransactionEntry objects.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
        - Received_debits
        - Transaction_entries
  /v1/treasury/transaction_entries/{id}:
    get:
      description: <p>Retrieves a TransactionEntry object.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
        - Received_debits
        - Transaction_entries
  /v1/treasury/transactions:
    get:
      description: <p>Retrieves a list of Transaction objects.</p>
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
        - Received_debits
        - Transaction_entries
        - Transactions
  /v1/treasury/transactions/{id}:
    get:
      description: <p>Retrieves the details of an existing Transa
      tags:
        - V1
        - Treasury
        - Credit_reversals
        - Credit_reversal
        - Debit_reversals
        - Debit_reversal
        - Financial_accounts
        - Financial_account
        - Features
        - Inbound_transfers
        - Id
        - Inbound_transfer
        - Cancel
        - Outbound_payments
        - Outbound_transfers
        - Outbound_transfer
        - Received_credits
        - Received_debits
        - Transaction_entries
        - Transactio
